### ISSUE TITLE
Add a TestNetWallet

### ISSUE THREAD

**Issue by readcash** [mainnet-cash/mainnet-js#10]
Add the TestNetWallet, so users can do the same thing as #3 and #9, but connecting to the a real testnet.

GRPC node: https://bchd-testnet.greyh.at:18335/

Two faucets I've found so far to get some sats:

https://developer.bitcoin.com/faucets/bch/
https://faucet.fullstack.cash/

I think in the end we'll have to setup our own testnet mining though.

**Comment by 2qx** [comment]
Almost done with this and #9 , bundle is built, connected to testnet in browser. 

Testnet transaction is just being rejected due to low priority.  Should be done with improved fees by EOD 2020-08-27
