### ISSUE TITLE
Other token are sent than specified in the tokenID

### ISSUE THREAD

**Issue by Telesfor1** [mainnet-cash/mainnet-js#102]
I have burned SLP-tokens in my wallet. When I try to send a burned token, different tokens are sent than the ones I specified in the tokenId.

**Comment by mainnet-pat** [comment]
Hi, Telesfor, thanks for reporting.

Can you please be more specific. Did you deliberately burned the tokens beforehand? What does it mean you tried to send a burnt token (at this time it is already plain bch)? What are token ids in question. Can you provide us the transaction ids where the issues happened?

pat.

**Comment by mainnet-pat** [comment]
@Telesfor1 is this issue connected to the other one from you?

**Comment by mainnet-pat** [comment]
Could not reproduce
