### ISSUE TITLE
by outgoing BCH transaction with from an address where I have SLP tokens, my tokens will be burned.

### ISSUE THREAD

**Issue by Telesfor1** [mainnet-cash/mainnet-js#103]
I noticed that through my outgoing BCH transaction with mainnet.cash, from an address where I have SLP tokens, my tokens are getting burned.

**Comment by mainnet-pat** [comment]
Hello Telesfor. Many apologies for that. In our current scheme the slp awareness is an opt-in since we can not afford to wait 5-10 seconds to get the responce from slpdb. To safely send bch please use `wallet.slpAware().send([...])`. We will write this in red in our documentation.

**Comment by mainnet-pat** [comment]
Use of slpAware is encouraged when working with slp enabled wallets. It remains an opt-in as Gspp integration is stalling.
