### ISSUE TITLE
Enrich and simplify transaction history.

### ISSUE THREAD

**Issue by 2qx** [mainnet-cash/mainnet-js#159]
A standard accounting ledger, for a payment app, might look something like this:
   
     
    Bob                        qz7xc0vl85n...ck65ffrs   Pizza             10        37.5
    Charlie                    qwvewjznp9l...flgktxc5   Trucking         150        47.5
    The Coffee Drip            qtxc5wvewjz...np9lflgk                     2.5      197.5

In short, it is a flat list of transactions, with where the payment went from/to, the amount, a running balance, and possibly a note.

To easily obtain this data from the blockchain, the following interface is proposed at `wallet/history`

    {
        "walletId": "wif, seed, etc...",
        "start?": 0,
        "count?": 25,
        "unit?":"sat"
    }
    
Which returns a list in revere chronological format of the most recent transactions, in the user specified unit, using the current balance to infer the running balance. 

    {
        "transactions": [
            {
                "cashaddr": "bitcoincash:qej23i4gb... ",
                "unit": "sat",
                "index": 0,
                "blockheight": 43093,
                "txId": "1e4ac1cb163ddf324e2c09f55c46ff0b6442a0d3548bb4f91772118a521cb89f:0",
                "value": -10000,
                "fee": 250,
                "balance": 4750
            },
            {
                "cashaddr": "bitcoincash:qej23i4gb... ",
                "unit": "sat",
                "index": 0,
                "blockheight": 43092,
                "txId": "1e6442a0d354ddf324e2c09f55c48bb4f917721184ac1cb1636ff0ba521cb89f:0",
                "value": 10000,
                "balance": 15000
            },
            {
                "cashaddr": "bitcoincash:qej23i4gb... ",
                "unit": "sat",
                "index": 1,
                "blockheight": 43090,
                "txId": "1e7721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f6442a0d3548bb4f91:1",
                "value": 5000,
                "balance": 5000
            }
        ]
    }

This data doesn't include any kind of notes, because notes are not stored on the blockchain for privacy reasons, but the transaction and index could be used by developers to track notes in a client side keystore db.

In addition, the `start` and `count` paging parameters wouldn't return the full transaction history by default, given that addresses might have hundreds or thousands of transactions, which the user isn't necessarily interested in the average use case..

Currently, getting a user friendly list of a wallet transactions can be a bit of a chore for developers over ElectrumX via electrum-cash. And mainnet-js doesn't have an easy way for developers to query this data.

There is an electrum call to query transactions by address, which returns the block height and transaction hash, as follows:

        {
            "jsonrpc": "2.0",
            "method": "blockchain.address.get_history",
            "params": [
                "qz7xc0vl85nck65ffrsx5wvewjznp9lflgktxc5878"
            ],
            "id": 0
        }

...

        {
            "height": 687929,
            "tx_hash": "c5afa073e2dd08896cf03abb5c36c49166dc285a916f2fb14714edb283c42ccc"
        },

...

Getting transaction details for **each** hash with a call similar to the below:

        {
            "jsonrpc": "2.0",
            "method": "blockchain.transaction.get",
            "params": [
                "c5afa073e2dd08896cf03abb5c36c49166dc285a916f2fb14714edb283c42ccc",
                true
            ],
            "id": 0
        }

Which returns a lot of information useful for a blockchain application, but that is less useful if someone just wants coffee:

        {
            "jsonrpc": "2.0",
            "result": {
                "blockhash": "00000000000000000163bb14e56b4a6d7cd59788bf58e7e2a54f8dc9052aba0d",
                "blocktime": 1620978209,
                "confirmations": 67629,
                "hash": "c5afa073e2dd08896cf03abb5c36c49166dc285a916f2fb14714edb283c42ccc",
                "hex": "020000000c1507afad76be9f001f2ed62b65ac60fbed718c5ab5197305c6eb40a76a44ae7a000000006a4730440220569bf0c7beace8d0feb99b9979d311f505a719d393da48371a2c4fa8d6cdf88802205ad269385afd0b2b32d5d3a28104f25b2325172f6b011c4e4e4385677509595a4121026f993254199598c8cb132b9ae48e646d3dea8698ae5f4ae88502157b313f504cfeffffff7f18022e99eee46b34bf276119b7454efe10ef62a69482bad93cb821717d690b060000006a47304402200119e64d92e15c515c5d5918580d4d697b0fe97b12279900ccd669401d985082022012d17325ccf1a1c8be97481764eabce7d3ca38cd247dce99e4a6b2b19f311f8c412102f6a90fde193921a2bb1004d8a8e6bd425b4a102adf253b075a9cad4d94a6c5aafeffffff057d5dc7af99fa22c1cc78a54e77a438d09869fb9efee08307a82073f1a733f6030000006a47304402201e54b057ed38757f7b2f01173320b927d2ed867f0ff59f38933f68b7285787cf02203ef3f9613a7eb8267ef7c65582ba0c9d88b5d1262c98cb73d4249fc195936bd24121021750f41ceb791b9a3f21589baa5b5a93b92427e6e930b8164022ede3165590b4feffffff0edcb473894a786a51f179cfe3bc9dad01c5940ebe1f2307abe65aabdded59dd020000006a473044022054e8669c793a761d33ce26a06ae80d6732aa151a97f26cddfb48008d16ad3c7202206130388600383ef15628fa6d2a412bff61ca87ca2b211589ddce38a703aada0a412103df890e7c9935ea5efcc1b03d075fe62d22b2a76f48cdfee543db6ae9f268fdaffeffffff9d4b4e2628014b57f7a8dd20edf8dde71b8bb6f64b9c11fbc2f7f9e058cab6bb080000006a473044022053f60c444f1921c0a613498168893254c2bbec5d0942a8ee306d5feccb395571022079d4237997172960749a25bee39fee130b2431277a36694ba4fd0d506bd1ba86412102c153aaf8851cc75893f356447bd5a635bfeb884f61605f9eb5c6c1fa8f577715feffffff5f54eaaf98c5473a0d950b487ac63866a22c75edaa1adad0f11187d33d71606c010000006a473044022066c5308733fba73575922d4c97a38e186df817728d4e5b863ff07edfb7e52c05022074fa9149aff239f57861b8a5200582742d8fd65d282622d7f0b64902f7deae4f41210303d4889dbef04ca256520c65d750d8eb58acab28495ec816b30f4662e2f94155fefffffff03c6de26ae5811df142b02660a7fc7696e2c0ebd27ae9eca7e9ddd677ac70fd000000006a47304402205c2f6e70ee202db68eb7982b6b1995bcfc109dced65046644ea2064c5910ca83022003bd132a10627e1167ec6312b4475d2af69b867c83304e106b859cb1227c9d77412103af7498cd4f8ceb68a502e2adf84fff3a05236a5096b2c15fe4cca490fdfc0b90feffffff6fa7644371a030ffa1c4821f183566ec94480ad4bae57a9a4d8be63bd1783be5020000006a473044022048ba9408eb020683133dbcd97d4c46f69a59e32c92197593bbab9c0ef2bb7a0602203489593723871b0a548cfbd4e29e2b2df852a164ec6e02ca8c8d43f2fdd7a5a04121028ff55e10da6634c706adb9851644f2da887fee4d9bdee57fb4810459227962e7feffffffc30cb5abfdaf2a983f059f71f70fa5b7e25643970afc969f821ebfb9f9ceb70b040000006a473044022046b32c70f59e83029b9331bd9c5f7ea3ff2c46d20000c8f9610ab34ddadff7ad02202aaac7e59a889fbe3a09202142efbd1dfc0f4c9256887c30f0129fadb1870341412102eb3b77f60ea930fff16659040fb31a1356a23ed7a255b85ab001faba55d26a14feffffffa6f7b502161e7491f5d24b924303c3bd73c2babbd4ff235106d427208820eab2000000006a4730440220715ed8089309da1517d217ded24d868f10d261497e43c57ecb03b695bd4e4e8502200c580cfe90292a687625fde419f15c56223237168964541df397104bd16ee12a4121025b012079580f5b25ad0b0502a30dd0abf00bf85264f64cf3bf29bd9fdec42d38feffffffe626854885c653f196295c01831ca87568faae4cd59578ba16c5168bd9920782010000006a47304402200d29bbc760c358cf59376ffcb127ce2784f3ae39e8c40ee9a12828340352753402203f69883966384a23be0ac82003bb57c7f54d2d7c92e078256be6617b50fd1f044121028b6913d25d50626258e7e19ea69db31bf81881bea9c1969bc718215b84f9ec2ffeffffff9118a8d02745fdde1c033315e0c80148780a0d942c33fefa0eaeb6394c31652a010000006a47304402206b84df982fc4fe7a636b3c5f2e361663ccde8ef5af4cc16d258573c1ca6f03c602200a8c0a870e37ebc9a9a47858bcec5e656a06ecacc8a77f43711c99d76abdf633412103b307bacec2065734ff8785ce1b43013a868c99e8e4245b07abe53baf993e8d18feffffff0204e048e80c0000001976a914bc6c3d9f3d278b6a8948e06a399974853097e9fa88acd5330f00000000001976a9141fd8cc2c3ec933c1c4076098b11b0f026df26f5388ac387f0a00",
                "locktime": 687928,
                "size": 1842,
                "time": 1620978209,
                "txid": "c5afa073e2dd08896cf03abb5c36c49166dc285a916f2fb14714edb283c42ccc",
                "version": 2,
                "vin": [
                    {
                        "scriptSig": {
                            "asm": "30440220569bf0c7beace8d0feb99b9979d311f505a719d393da48371a2c4fa8d6cdf88802205ad269385afd0b2b32d5d3a28104f25b2325172f6b011c4e4e4385677509595a[ALL|FORKID] 026f993254199598c8cb132b9ae48e646d3dea8698ae5f4ae88502157b313f504c",
                            "hex": "4730440220569bf0c7beace8d0feb99b9979d311f505a719d393da48371a2c4fa8d6cdf88802205ad269385afd0b2b32d5d3a28104f25b2325172f6b011c4e4e4385677509595a4121026f993254199598c8cb132b9ae48e646d3dea8698ae5f4ae88502157b313f504c"
                        },
                        "sequence": 4294967294,
                        "txid": "7aae446aa740ebc6057319b55a8c71edfb60ac652bd62e1f009fbe76adaf0715",
                        "vout": 0
                    },
                    {
                        "scriptSig": {
                            "asm": "304402200119e64d92e15c515c5d5918580d4d697b0fe97b12279900ccd669401d985082022012d17325ccf1a1c8be97481764eabce7d3ca38cd247dce99e4a6b2b19f311f8c[ALL|FORKID] 02f6a90fde193921a2bb1004d8a8e6bd425b4a102adf253b075a9cad4d94a6c5aa",
                            "hex": "47304402200119e64d92e15c515c5d5918580d4d697b0fe97b12279900ccd669401d985082022012d17325ccf1a1c8be97481764eabce7d3ca38cd247dce99e4a6b2b19f311f8c412102f6a90fde193921a2bb1004d8a8e6bd425b4a102adf253b075a9cad4d94a6c5aa"
                        },
                        "sequence": 4294967294,
                        "txid": "0b697d7121b83cd9ba8294a662ef10fe4e45b7196127bf346be4ee992e02187f",
                        "vout": 6
                    },
                    {
                        "scriptSig": {
                            "asm": "304402201e54b057ed38757f7b2f01173320b927d2ed867f0ff59f38933f68b7285787cf02203ef3f9613a7eb8267ef7c65582ba0c9d88b5d1262c98cb73d4249fc195936bd2[ALL|FORKID] 021750f41ceb791b9a3f21589baa5b5a93b92427e6e930b8164022ede3165590b4",
                            "hex": "47304402201e54b057ed38757f7b2f01173320b927d2ed867f0ff59f38933f68b7285787cf02203ef3f9613a7eb8267ef7c65582ba0c9d88b5d1262c98cb73d4249fc195936bd24121021750f41ceb791b9a3f21589baa5b5a93b92427e6e930b8164022ede3165590b4"
                        },
                        "sequence": 4294967294,
                        "txid": "f633a7f17320a80783e0fe9efb6998d038a4774ea578ccc122fa99afc75d7d05",
                        "vout": 3
                    },
                    {
                        "scriptSig": {
                            "asm": "3044022054e8669c793a761d33ce26a06ae80d6732aa151a97f26cddfb48008d16ad3c7202206130388600383ef15628fa6d2a412bff61ca87ca2b211589ddce38a703aada0a[ALL|FORKID] 03df890e7c9935ea5efcc1b03d075fe62d22b2a76f48cdfee543db6ae9f268fdaf",
                            "hex": "473044022054e8669c793a761d33ce26a06ae80d6732aa151a97f26cddfb48008d16ad3c7202206130388600383ef15628fa6d2a412bff61ca87ca2b211589ddce38a703aada0a412103df890e7c9935ea5efcc1b03d075fe62d22b2a76f48cdfee543db6ae9f268fdaf"
                        },
                        "sequence": 4294967294,
                        "txid": "dd59edddab5ae6ab07231fbe0e94c501ad9dbce3cf79f1516a784a8973b4dc0e",
                        "vout": 2
                    },
                    {
                        "scriptSig": {
                            "asm": "3044022053f60c444f1921c0a613498168893254c2bbec5d0942a8ee306d5feccb395571022079d4237997172960749a25bee39fee130b2431277a36694ba4fd0d506bd1ba86[ALL|FORKID] 02c153aaf8851cc75893f356447bd5a635bfeb884f61605f9eb5c6c1fa8f577715",
                            "hex": "473044022053f60c444f1921c0a613498168893254c2bbec5d0942a8ee306d5feccb395571022079d4237997172960749a25bee39fee130b2431277a36694ba4fd0d506bd1ba86412102c153aaf8851cc75893f356447bd5a635bfeb884f61605f9eb5c6c1fa8f577715"
                        },
                        "sequence": 4294967294,
                        "txid": "bbb6ca58e0f9f7c2fb119c4bf6b68b1be7ddf8ed20dda8f7574b0128264e4b9d",
                        "vout": 8
                    },
                    {
                        "scriptSig": {
                            "asm": "3044022066c5308733fba73575922d4c97a38e186df817728d4e5b863ff07edfb7e52c05022074fa9149aff239f57861b8a5200582742d8fd65d282622d7f0b64902f7deae4f[ALL|FORKID] 0303d4889dbef04ca256520c65d750d8eb58acab28495ec816b30f4662e2f94155",
                            "hex": "473044022066c5308733fba73575922d4c97a38e186df817728d4e5b863ff07edfb7e52c05022074fa9149aff239f57861b8a5200582742d8fd65d282622d7f0b64902f7deae4f41210303d4889dbef04ca256520c65d750d8eb58acab28495ec816b30f4662e2f94155"
                        },
                        "sequence": 4294967294,
                        "txid": "6c60713dd38711f1d0da1aaaed752ca26638c67a480b950d3a47c598afea545f",
                        "vout": 1
                    },
                    {
                        "scriptSig": {
                            "asm": "304402205c2f6e70ee202db68eb7982b6b1995bcfc109dced65046644ea2064c5910ca83022003bd132a10627e1167ec6312b4475d2af69b867c83304e106b859cb1227c9d77[ALL|FORKID] 03af7498cd4f8ceb68a502e2adf84fff3a05236a5096b2c15fe4cca490fdfc0b90",
                            "hex": "47304402205c2f6e70ee202db68eb7982b6b1995bcfc109dced65046644ea2064c5910ca83022003bd132a10627e1167ec6312b4475d2af69b867c83304e106b859cb1227c9d77412103af7498cd4f8ceb68a502e2adf84fff3a05236a5096b2c15fe4cca490fdfc0b90"
                        },
                        "sequence": 4294967294,
                        "txid": "fd70ac77d6dde9a7ece97ad2ebc0e29676fca76026b042f11d81e56ae26d3cf0",
                        "vout": 0
                    },
                    {
                        "scriptSig": {
                            "asm": "3044022048ba9408eb020683133dbcd97d4c46f69a59e32c92197593bbab9c0ef2bb7a0602203489593723871b0a548cfbd4e29e2b2df852a164ec6e02ca8c8d43f2fdd7a5a0[ALL|FORKID] 028ff55e10da6634c706adb9851644f2da887fee4d9bdee57fb4810459227962e7",
                            "hex": "473044022048ba9408eb020683133dbcd97d4c46f69a59e32c92197593bbab9c0ef2bb7a0602203489593723871b0a548cfbd4e29e2b2df852a164ec6e02ca8c8d43f2fdd7a5a04121028ff55e10da6634c706adb9851644f2da887fee4d9bdee57fb4810459227962e7"
                        },
                        "sequence": 4294967294,
                        "txid": "e53b78d13be68b4d9a7ae5bad40a4894ec6635181f82c4a1ff30a0714364a76f",
                        "vout": 2
                    },
                    {
                        "scriptSig": {
                            "asm": "3044022046b32c70f59e83029b9331bd9c5f7ea3ff2c46d20000c8f9610ab34ddadff7ad02202aaac7e59a889fbe3a09202142efbd1dfc0f4c9256887c30f0129fadb1870341[ALL|FORKID] 02eb3b77f60ea930fff16659040fb31a1356a23ed7a255b85ab001faba55d26a14",
                            "hex": "473044022046b32c70f59e83029b9331bd9c5f7ea3ff2c46d20000c8f9610ab34ddadff7ad02202aaac7e59a889fbe3a09202142efbd1dfc0f4c9256887c30f0129fadb1870341412102eb3b77f60ea930fff16659040fb31a1356a23ed7a255b85ab001faba55d26a14"
                        },
                        "sequence": 4294967294,
                        "txid": "0bb7cef9b9bf1e829f96fc0a974356e2b7a50ff7719f053f982aaffdabb50cc3",
                        "vout": 4
                    },
                    {
                        "scriptSig": {
                            "asm": "30440220715ed8089309da1517d217ded24d868f10d261497e43c57ecb03b695bd4e4e8502200c580cfe90292a687625fde419f15c56223237168964541df397104bd16ee12a[ALL|FORKID] 025b012079580f5b25ad0b0502a30dd0abf00bf85264f64cf3bf29bd9fdec42d38",
                            "hex": "4730440220715ed8089309da1517d217ded24d868f10d261497e43c57ecb03b695bd4e4e8502200c580cfe90292a687625fde419f15c56223237168964541df397104bd16ee12a4121025b012079580f5b25ad0b0502a30dd0abf00bf85264f64cf3bf29bd9fdec42d38"
                        },
                        "sequence": 4294967294,
                        "txid": "b2ea20882027d4065123ffd4bbbac273bdc30343924bd2f591741e1602b5f7a6",
                        "vout": 0
                    },
                    {
                        "scriptSig": {
                            "asm": "304402200d29bbc760c358cf59376ffcb127ce2784f3ae39e8c40ee9a12828340352753402203f69883966384a23be0ac82003bb57c7f54d2d7c92e078256be6617b50fd1f04[ALL|FORKID] 028b6913d25d50626258e7e19ea69db31bf81881bea9c1969bc718215b84f9ec2f",
                            "hex": "47304402200d29bbc760c358cf59376ffcb127ce2784f3ae39e8c40ee9a12828340352753402203f69883966384a23be0ac82003bb57c7f54d2d7c92e078256be6617b50fd1f044121028b6913d25d50626258e7e19ea69db31bf81881bea9c1969bc718215b84f9ec2f"
                        },
                        "sequence": 4294967294,
                        "txid": "820792d98b16c516ba7895d54caefa6875a81c83015c2996f153c685488526e6",
                        "vout": 1
                    },
                    {
                        "scriptSig": {
                            "asm": "304402206b84df982fc4fe7a636b3c5f2e361663ccde8ef5af4cc16d258573c1ca6f03c602200a8c0a870e37ebc9a9a47858bcec5e656a06ecacc8a77f43711c99d76abdf633[ALL|FORKID] 03b307bacec2065734ff8785ce1b43013a868c99e8e4245b07abe53baf993e8d18",
                            "hex": "47304402206b84df982fc4fe7a636b3c5f2e361663ccde8ef5af4cc16d258573c1ca6f03c602200a8c0a870e37ebc9a9a47858bcec5e656a06ecacc8a77f43711c99d76abdf633412103b307bacec2065734ff8785ce1b43013a868c99e8e4245b07abe53baf993e8d18"
                        },
                        "sequence": 4294967294,
                        "txid": "2a65314c39b6ae0efafe332c940d0a784801c8e01533031cdefd4527d0a81891",
                        "vout": 1
                    }
                ],
                "vout": [
                    {
                        "n": 0,
                        "scriptPubKey": {
                            "addresses": [
                                "bitcoincash:qz7xc0vl85nck65ffrsx5wvewjznp9lflgktxc5878"
                            ],
                            "asm": "OP_DUP OP_HASH160 bc6c3d9f3d278b6a8948e06a399974853097e9fa OP_EQUALVERIFY OP_CHECKSIG",
                            "hex": "76a914bc6c3d9f3d278b6a8948e06a399974853097e9fa88ac",
                            "reqSigs": 1,
                            "type": "pubkeyhash"
                        },
                        "value": 554.36697604
                    },
                    {
                        "n": 1,
                        "scriptPubKey": {
                            "addresses": [
                                "bitcoincash:qq0a3npv8myn8swyqasf3vgmpupxmun02vcrvzppkm"
                            ],
                            "asm": "OP_DUP OP_HASH160 1fd8cc2c3ec933c1c4076098b11b0f026df26f53 OP_EQUALVERIFY OP_CHECKSIG",
                            "hex": "76a9141fd8cc2c3ec933c1c4076098b11b0f026df26f5388ac",
                            "reqSigs": 1,
                            "type": "pubkeyhash"
                        },
                        "value": 0.00996309
                    }
                ]
            },
            "id": 0
        }

**Comment by JeremyEllingham** [comment]
Looks really good to me, would certainly be a super useful feature.

**Comment by 2qx** [comment]
Wrapping this up.  

' landed on a simple from/to schema. Change is omitted by default. It can be clipped to reduce network traffic to the client, but if used client side, it **does** make a request for every transaction, and every utxo.

        {
          "transactions": [
            {
              "from": "bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys0d2lessf",
              "to": "bchtest:qpq84h3f25w2h4a6wl0kls5y62xcefvhyywqzm8fh6",
              "unit": "sat",
              "index": 0,
              "blockheight": -1,
              "txn": "211e5e2ca1653c59d0120205935ce0d00e01c237bf4f2c3d77f056b62a5e853c",
              "txId": "211e5e2ca1653c59d0120205935ce0d00e01c237bf4f2c3d77f056b62a5e853c:i:0",
              "value": -1000,
              "fee": 220,
              "balance": 8780
            },
            {
              "from": "bchtest:qzl7ex0q35q2d6aljhlhzwramp09n06fry8ssqu0qp",
              "to": "bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys0d2lessf",
              "unit": "sat",
              "index": 0,
              "blockheight": 0,
              "txn": "aa55ef1404e01f6166b2eac018867e8dc1b0b7816d3f43917cdffdb5dc10b648",
              "txId": "aa55ef1404e01f6166b2eac018867e8dc1b0b7816d3f43917cdffdb5dc10b648:o:0",
              "value": 10000,
              "balance": 10000,
              "fee": 0
            }
          ]
        }
