### ISSUE TITLE
Faucet throws Alert error related to smartBCH when metamask is not installed.

### ISSUE THREAD

**Issue by 2qx** [mainnet-cash/mainnet-js#161]
**Warning: don't disclose private information, take extra care posting screenshots or copying text, as it may contain private keys, i.e. walletIds, walletInfo**

**Describe the context**
 - Webpage: https://rest-unstable.mainnet.cash/faucet.html

**Describe the bug**

When loading:

https://rest-unstable.mainnet.cash/faucet.html

An alert is thrown related to network being unavailable.

**To Reproduce**
Open faucet in browser.

**Expected behavior**
Should hide SmartBCH or give instructions for enabling if not available.

**Additional context**

Akad via Telegram.

**Comment by mainnet-pat** [comment]
Fixed in 1.0.0
