### ISSUE TITLE
bug getAllNftTokenBalances()

### ISSUE THREAD

**Issue by mr-zwets** [mainnet-cash/mainnet-js#175]
Currently `wallet.getAllNftTokenBalances()` returns an object with as keys the tokenId and with the value the number of UTXOs containing that tokenId.

The problem is that it does not only count the UTXOs with an NFT of that tokenId but also fungibles.
I had been told I could use this as a "Metamask like query. Like you hold 100 Apes".
I would like to display multiple nfts from the same tokenId as a group in my webwallet but because fungible token UTXOs are also counted I cannot use `wallet.getAllNftTokenBalances()`.

Hope this behavior gets changed so it can become used in the way it was intended.

**Comment by mainnet-pat** [comment]
Reopening for retest
