### ISSUE TITLE
Transaction and Utxo webooks

### ISSUE THREAD

**Issue by 2qx** [mainnet-cash/mainnet-js#21]
- Specify REST endpoints for webhooks based on the sample below, updating or modifying only as necessary.
- Implement core library 
- Add tests for all library functionality 
- Add express service endpoints 
- Add tests for express endpoints using a mock client library.

```
/api/v1/wallet/watch_balance                      w.watchBalance()
/api/v1/wallet/wait_for_transaction               w.waitForTransaction()
```

**Comment by mainnet-pat** [comment]
Watching balances and addresses is available in node, js (websockets) and rest (webhooks)
