### ISSUE TITLE
New wallet, named wallets (+basic REST API)

### ISSUE THREAD

**Issue by readcash** [mainnet-cash/mainnet-js#7]
Though, of course, anyone is free to take this task, but I'd prefer @2qx to take it, since he seems to have a lot of understanding how to do this well and this task is the basis of ALL of our future work. Don't worry, as soon as we're done with some basic stuff, there will be plenty of tasks.

This issue calls to implement the creation of a new wallet and its corresponding REST API:

```
const w = new RegTestWallet();
console.log(w.wif);
// cNfsP... (random every time)
```

and named wallets:

```
const w1 = new RegTestWallet('username1');
console.log(w1.wif);
// abcdef.. (random first time)

const w2 = new RegTestWallet('username1');
console.log(w2.wif);
// abcdef.. (same as above)

const w2 = new RegTestWallet('username2');
console.log(w2.wif);
// fghi.. (random)
```

It should store its private key (in WIF format I guess?) in IndexedDB in the browser by name. The usefulness of this comes when the same browser is used by different people (or one person) logging in to different accounts on the same site. i.e. on read.cash you can have multiple usernames, each one having its own wallet. Without this any person who tries to create a new account on any site will end up with the same wallet on every account (which is incorrect). read.cash doesn't actually store it by username, but rather by a hash of user.id + secret string, so that it's harder to guess. But it will be just a recommendation.

Also, we need to start doing the node.js interface, so similarly we need to implement 

```
POST /api/v1/wallet
JSON request body: {"type":"wif", "network":"regtest"}
```

returning JSON:
```
{"wallet": "wif:regtest:abc12345", "wif": "abc12345", "cashaddr": "..."}
```

This call is stateless, so it doesn't save anything, just returns a random wallet. `abc12345` is the actual random WIF, like `cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6`.

....and a named version of the call:

```
POST /api/v1/wallet
{"type":"wif", "network":"regtest", "name": "username1"}
```

returning
```
{"wallet": "wif:regtest:username1", "wif": "abc12345", "cashaddr": "..."}
```

But this call is stateful, meaning each time user calls for `{"type":"wif", "network":"regtest", "name": "username1"}` he gets the same wallet back.

`wallet` in return is the [serialization](https://github.com/mainnet-cash/project/issues/2) of the wallet data that we would need in future calls - it's important for us to know that this is a WIF wallet (as opposed to HD wallets), that it's for regtest and what its WIF is... for named wallets we don't need to store WIF in the `wallet`, since we store WIF on server.

So, now a future call of 

```
POST /api/v1/send
{"wallet": "wif:regtest:abcd123", "to" ...}
```

...we already know what to do.

Some considerations for storage: for browser it's surely IndexedDB (though https://dexie.org/ looks like a much nicer wrapper API and pretty small). 

For server-side node.js, I have no idea what we should use. I would probably avoid using sqlite, because some servers could see heavy use, that means having to run multiple workers of node.js, and SQLite won't work well with that. So maybe it's PostgreSQL or mySQL.. This looks interesting though: https://github.com/indexeddbshim/IndexedDBShim

Yeah and I guess if we're talking Postgres/mySQL - then we'll need docker-compose anyway.

Tests are required.

### -- $1,000 bounty --

The bounty is paid in BCH from the funds collected via https://github.com/mainnet-cash/mainnet-js . To claim the bounty, please do the following: 

1) if this task requires coding in TypeScript, first you need to complete the test task by sending a private message to ReadCash via [Slack link here](https://github.com/mainnet-cash/project#where-are-we); 

2) after you have completed the test task once, tell us that you are working on this task and how long it is going to take, like this: "I'll take it. I expect it to be done in 2 days". If that time close to expire and you haven't finished it yet, you can write something like "It'll take 2 more days", otherwise anyone else is free to take the task); 

3) send a Pull Request or publish the solution here as described in the issue. 
Good luck! If you think that bounty is way too small, please notify me about it and we can discuss. A bounty will be paid via the chaintip bot.

**Comment by readcash** [comment]
@2qx Maybe we can avoid having to install mySQL/PostgreSQL and use something like https://github.com/Venemo/node-lmdb ? I think that would be pretty neat, since then when BCHD implements SLP token database, we can be zero-dependencies for development again. And it seems that LMDB supports multi-process write, so we're clear in this regard too.

**Comment by 2qx** [comment]
What about https://github.com/nimiq/jungle-db ?

Seems like it was designed exactly for this problem.

**Comment by readcash** [comment]
Seems like a good choice too.

**Comment by readcash** [comment]
@2qx @chaintip

**Comment by chaintip** [comment]
@2qx, you've [been sent](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4zaavcr3seylyu4hzcl56ljh8tec47zdapqd) `3.65070093 BCH`| `~ 996.45 USD` by @readcash via [chaintip](http://www.chaintip.org).
