### ISSUE TITLE
missing change log

### ISSUE THREAD

**Issue by theRealBitcoinClub** [mainnet-cash/mainnet-js#71]
I would like to see a change log in the README so that I can follow your efforts to see if a certain release actually affects my use cases.

**Comment by 2qx** [comment]
Hello @theRealBitcoinClub , We've started a running log here:

https://github.com/mainnet-cash/mainnet-js/blob/master/RELEASE_NOTES.txt

Should have updates for future releases.

**Comment by theRealBitcoinClub** [comment]
Thanks!

Enviado desde ProtonMail móvil

-------- Mensaje original --------
