### ISSUE TITLE
Build process for the browser library

### ISSUE THREAD

**Issue by readcash** [mainnet-cash/mainnet-js#9]
Create a yarn command that will build dist/mainnet-0.0.1-rc.js (where 0.0.1 is our version that is stored somewhere).

Ensure it's working by creating a simple HTML file with a <script> tag that will replicate the test from #3 but inside the browser.

**Comment by 2qx** [comment]
Starting this one.  Should be done today (2020-08-25).

**Comment by 2qx** [comment]
Resolved by PR 17
